### ISSUE TITLE
Better naming for location codes

### ISSUE THREAD

**Issue by Importantus** [Draculente/mensa-api#12]
Since the api is designed to include other cities than Lübeck, location codes like "CA" or "ME" are a bit shortsighted. Maybe we could prefix them with the official city code (the one from the licence plates), so "CA" would be "HL_CA"?

**Comment by hoppjan** [comment]
Since this is a breaking change, maybe the old codes could continue to be valid for a while?

**Comment by Draculente** [comment]
As version two is still super new, I'm too lazy to implement the extended validity of the old location-codes.
