### ISSUE TITLE
Allergens not under /allergens but /allergenes

### ISSUE THREAD

**Issue by hoppjan** [Draculente/mensa-api#14]
There is a typo in the URL:
- does not work, but should: https://speiseplan.mcloud.digital/v2/allergens?location=HL_ME
- does work, but is French: https://speiseplan.mcloud.digital/v2/allergenes?location=HL_ME

**Comment by Draculente** [comment]
Ooops. Well know I will have to support both the typo and the correct string 🙄. But I fixed it...
