### ISSUE TITLE
Wrong Employee Pricing

### ISSUE THREAD

**Issue by budel** [Draculente/mensa-api#16]
Hej,

first of all thank you for this comprehensive API!
Unfortunately the employee prices are wrong since Version 2. 
Let's take todays date as an example. When I curl https://speiseplan.mcloud.digital/v2/meals?location=HL_ME&date=2024-09-26 I get {students":2.55,"employees":2.55,"guests":5.05} for the first meal. A look on the website tells me otherwise:
![Screenshot_20240926_211850_Fennec](https://github.com/user-attachments/assets/58047dbb-6115-4246-ae5e-a0e9052c2a49)
It seems that the student price is detected twice...

**Comment by Draculente** [comment]
Ooops, what a stupid bug 😅.
I fixed it in commit e79c7acc05cc294b02ee50da71155a9ac5aeb264. 

PS: I'm sorry for shutting down the first version of the API so abruptly, I didn't realize anyone else was using it. I promise to do better in the future 😇.
